### ISSUE TITLE
CraftTweaker chopping block bug, always get 10 

### ISSUE THREAD

**Issue by MechWarrior99** [gigaherz/Survivalist#14]
While testing the crafttweaker support in the newest build, I discovered that you always seem to get 10.

It does not matter what I set the output amount to be, it will always give me 10 of the output item.

**Comment by gigaherz** [comment]
Did you restart the game after editing the script? If you add a recipe that already exists, it won't replace it (it just adds another entry at the end, which never gets used because the old entry is matched first), and I still haven't implemented a way to "reset" the list of recipes when crafttweaker reloads.

**Comment by MechWarrior99** [comment]
Oh, yeah restarting the game worked.

**Comment by gigaherz** [comment]
You could also have a removeRecipe right before adding it, to make sure the old recipes are removed first.
