### ISSUE TITLE
Mod ore compatibility request

### ISSUE THREAD

**Issue by Silvrus** [gigaherz/Survivalist#2]
Hello, love the mod, it's working very well in the UHS pack I'm building. I love the iron/gold ore mechanic, really slows down the early game and pushes people to get silk touch. I'd like to request this mechanic be extended to common mod ores of copper, tin, lead, and silver. I understand specific ores such as those from TechReborn wouldn't be feasible, but the "common" mod ores would be good. I feel this would greatly benefit survival based modpacks that have tech mods in them. Thanks, and keep up the great work!

**Comment by gigaherz** [comment]
Yeah that was on my TODO list, I was just putting it off. you are in luck, though, since I have been working on a new feature (chopping block, which splits logs into planks, and planks into sticks, at a rate depending on the quality of the tool), so I may try to get some more ores working too. Any specific mods you'd like me to test for compatibility?

**Comment by Silvrus** [comment]
Currently I'm using TechReborn and Forestry, but have Forestry's copper and tin turned off in favor of TechReborn. I would say IC2, but they're handling their ore using metadata or NBT and I'm not sure how involved it would be to work with. The chopping block sounds great, are you planning to modify the base amount of planks you get or the log drop from punching trees? Another mod I'm using drops bark and 1-3 planks when punching trees, requiring an axe to get the logs.

**Comment by gigaherz** [comment]
Thanks, I'll look at those. Metadata-based subitems are ok, NBT-based subitems are annoying to work with.

And regarding the chopping block: by default I disable the log->planks recipe, and replace it with log->chopblock, while at the same time creating chopblock recipes equivalent to the log->planks recipe I just removed. With that setup, anyone with at least an Iron axe will get 4 planks.

**Comment by Silvrus** [comment]
Awesome, thanks for responding so quickly. The chopblock sounds like a great idea, look forward to checking it out.

**Comment by Silvrus** [comment]
A thought occurred to me, is the chopping block going to be compatible with say Tinker's?

**Comment by gigaherz** [comment]
Compatible how?

**Comment by Silvrus** [comment]
I'm probably not understanding properly. Compatible in that it will recognize the material level of modded tools, i.e. Tinker's hatchets. I imagine that wouldn't be on your side but rather the other mod properly registering their tool levels though.

**Comment by gigaherz** [comment]
Oh, yes I just call getHarvestLevel("axe"), it's up to the item to decide what number to return (-1 means it's as good as hands, 0 is wooden/gold, 1 is iron, etc).

**Comment by gigaherz** [comment]
v1.5.0 is out! Bug reports are appreciated! ;P

**Comment by Silvrus** [comment]
Awesome, thanks for adding those ores so quickly. Chopping block is great, the hit box seems a bit off though, as in it has a small detection area or something. Kind of have hit around a couple of times to get the planks to pop up, otherwise fantastic idea.

**Comment by gigaherz** [comment]
That's because you HAVE to hit it repeatedly. I haven't been able to figure out how to make it work with continuous holding the button, yet.

**Comment by Silvrus** [comment]
Yeah, I figured that out, I was just editing my comment when you posted, lol. Great job, and I love the deterioration of the chopping block, nice touch!

**Comment by Silvrus** [comment]
Hey bud, hate to re-open, I know you're busy, but I was wondering if you could add 1 more mod to the compatability? I found WTF's Expedition mod, which overall is great but in the mod's tweaking of oregen it actually replaces vanilla ores with it's own, which bypasses the ore rocks dropped. From the dev:
"My ore blocks are actually separate blocks from the vanilla ores.  All you should need to do is get the survivalist mod to recognise my ores, and swap out the drops.  If there's a config option to add blocks to it's ore system, that should do it, assuming that survivalist isn't doing something hacky that will cancel the dense ore function."
If you've time can you take a look? Thanks man!

**Comment by gigaherz** [comment]
Hmm, the way it works now, is that whenever anyone harvests a block, I scan the dropped items, and replace the ones matching with the rocks. However, I didn't consider the possibility of alternative gold/iron. I'll look at it later when I get back from work, and see what I can do about it.

**Comment by gigaherz** [comment]
I have had a look at it, the issue is that the special harvesting of the "dense ores" don't actually fire the harvest event, so I don't have a way to substitute those drops. For it to work, I'd need the mod to directly or indirectly call `ForgeEventFactory.fireBlockHarvesting` similar to how the standard `dropBlockAsItemWithChance` or `harvestBlock` do. Ideally the expedition mod would simply use the existing harvestBlock logic, or call dropBlockAsItem whenever it's about to harvest, this way it would follow all the standard procedures, even if they were to change in the future.

I managed to find the source code to that mod, and I see that they [explicitly disabled the harvest event](https://github.com/WhiskyTangoFawks/Expedition/blob/master/1-9Forge/src/main/java/wtf/core/blocks/AbstractBlockDerivative.java#L60). If it remains that way, there isn't much I can do.

Feel free to forward this information to them.

**Comment by Silvrus** [comment]
Thanks for looking into this mate, I sent him what you said, we'll see if there's anything that can be done.

**Comment by Silvrus** [comment]
He said you were right and that it should be firing that event. He's going to check into it. Thanks again.
