### ISSUE TITLE
Tinkers Construct crash when hitting chopping block

### ISSUE THREAD

**Issue by Drakoflame** [gigaherz/Survivalist#25]
Every time I try to hit a chopping block with a tinkers construct tool, I keep crashing. I think that it might have to do with the chopping block not knowing what "level" a tinkers tool is at, so it does't know the correct amount of planks to give back. But then again, I can't code, so I have no idea, instead, have a crash log :D http://pastebin.com/2GA8ygEm

**Comment by gigaherz** [comment]
Interesting guess, but it's wrong. ;P

Because of the way the chopping block works, I can't give `getHarvestLevel` a target block to test against, which seems to be crashing TiCon. This means the bug is not in Survivalist, but in TiCon, since that parameter is Nullable.

I will verify if my guess is correct (I have to get a 1.10.2 environment working, since TiCon doesn't appear to have 1.11.x builds), and report back.

**Comment by gigaherz** [comment]
The issue happens here: https://github.com/SlimeKnights/TinkersConstruct/blob/master/src/main/java/slimeknights/tconstruct/library/utils/ToolHelper.java#L179
This seems to only run when you have something in your offhand slot.
You may want to report this to the TiCon repository instead.
