### ISSUE TITLE
[Request] 

### ISSUE THREAD

**Issue by Shane371** [gigaherz/Survivalist#30]
Config request - Tie rock and ore rocks to a mining level. Mods great early game and you can still get ore with silk touch but it would be great if you could progress past the ore nerf.  

Also, not really the place to ask but anyone know a mod with a simple RF sawmill? Only things I could find without making my own or adding recipes is thermal expansion and rocketry.

**Comment by gigaherz** [comment]
Just to make sure I understand your request correctly: you'd like tools over a certain mining level (such as like, "iron and up" or similar), to mine full ores/blocks instead of rocks? If so, I'd have to think about it.

And what are you picturing for a sawmill? A machine that cuts wood->planks->sticks and such, but automated? And if so, how would you power it? Coal? I'm thinking this could actually be an interesting addition to the mod, to make wood less grindy after earlygame.

**Comment by Shane371** [comment]
I like the way your mod adds to the early game but if you are playing with tech mods it becomes a bit much to rely on the chopping block and ruffly cutting ores by half.  Now that I have been thinking about it its not as big of an issue. Probably going to add in recipes to a later machine that compresses 4+some cobble back into the ore. Silktouch still grabs the ore block and most quarrys allow that upgrade. Just looking for a way to balance things out mid/late game as other mods(for the most part) balance around 1 ore to 1 ingot.

Coal sawmill would be fine if hoppers/pipes work with it. RF option would be a bonus but not needed. Was a bit surprised at how few mods have a "Sawmill" and it feels wrong to have a alloy/sag/ect cutting planks and sticks :P

**Comment by gigaherz** [comment]
It has taken a long time but v2.0 for 1.12(1) will have a Sawmill. I'm very close to releasing, so I'm going through the issue list to see if there's anything I have missed.

Note that I will not have a mining level that drops ores, that's what silk touch is for.
