### ISSUE TITLE
Flint tools seem a bit too good (config?)

### ISSUE THREAD

**Issue by WolfieWaffle** [gigaherz/Survivalist#40]
I think  what you were going for was making tools better than stone, but often times stone and wood tools are disabled in survival packs anyways, making it so the first tool you get is sometimes better than other tools. Having a config to change this would be useful, but I also have tried modding myself and realize that changing mining speeds and stuff from a config file might have problems. Or at least I think it does, not exactly sure why. Or you could just make them more like stone tools, but if that's not your vision for the mod that's fine, its not a major issue.

**Comment by gigaherz** [comment]
In what area are they too good, though? They are only barely slightly better than stone:
* Harvest level is 1, like stone
* Durability is 150, compared with stone's 131
* Mining efficiency is 5 (stone is 4, iron is 6)
* Damage vs entities is 1.5 (stone is 1, iron is 2)
* Enchantability is 5, like stone

I can't make it change based on config (the items and blocks are registered before the config loads, these days, and it's unsafe to make changes like this based on config anyhow).

My goal was indeed to make them something in between stone and iron. I'm not sure what the problem is that you are seeing...

**Comment by WolfieWaffle** [comment]
I guess its fine then, maybe I missed something. I felt like it ended up being faster than tconstruct copper, but I can test that now, one sec

**Comment by WolfieWaffle** [comment]
hm, doesn't look like its any faster. I don't know what I was thinking, must have been some other nod. Nevermind then XD

**Comment by gigaherz** [comment]
Feel free to reopen if you decide there is a problem in the end. ;P
