### ISSUE TITLE
Thermal Expansion Sawmill

### ISSUE THREAD

**Issue by Fortist** [gigaherz/Survivalist#85]
It seems that because you changed the log to plank recipe into log to chopping block, the TE sawmill only makes chopping blocks with logs, or for modded wood there is no recipe. I really rather not do every log to plank recipe by hand in crafttweaker

Im probably gonna test some things and see if that fixes it. 
Though as a side note, can disabling things in the config actually DISABLE the things?

**Comment by gigaherz** [comment]
Technically, I don't change the recipe. I register recipes for log->chopblock, and then IF ENABLED, I disable the recipes for log->planks. Because I wanted to support the new advancement system, I couldn't make registering the chopblock recipes configurable, because advancements don't support configuration -- if mc tries to load an advancement json that references a missing recipe, advancements stop loading, and any remaining advancements will be missing. Because of that, some of the settings are gone in 1.12. 

That said, if some config setting doesn't work, that is supposed to work, then it's a bug that I need to fix.
